### ISSUE TITLE
Do you mind if Implement this in my own pathtracer?

### ISSUE THREAD

**Issue by Pjbomb2** [yangrc1234/VolumeCloud#14]
Ive been looking for clouds or methods of clouds for awhile now but could never get them fined tuned enough to look good, so I was wondering if I could use your clouds here in my own project? Credits to the cloud code would of course be given to you, and stated in all readmes and in the code itself, but I wanted to make sure this was ok with you first

**Comment by yangrc1234** [comment]
Definitely OK!
