### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by theprotonfactor** [yangrc1234/VolumeCloud#2]
This is super cool! I think I can make some improvements here and there. The upscale and reprojection especially, but what license is this under? Can I use it in my commercial game?

**Comment by yangrc1234** [comment]
Added MIT License.
You're welcome to do anything you want with this.

**Comment by theprotonfactor** [comment]
Awesome! Thank you so much. If I make a good fix for the blur issue I'll be sure to make a pull request
