### ISSUE TITLE
HDRP support??

### ISSUE THREAD

**Issue by davoodkharmanzar** [yangrc1234/VolumeCloud#3]
hello dear,
this is nice clouds :]
but does it support on HDRP?

**Comment by yangrc1234** [comment]
No. 
When I started this project, HDRP doesn't exists.  
But I will try to add support for HDRP once this project looks no problem on the standard pipeline. 
As you know HDRP is very very different from standard pipeline, so it might take a long time get it done(haven't checked it, but as far as I know, HDRP has a unique pipeline for volume rendering like the one in Frostbite).
Thank you for your concern.
