### ISSUE TITLE
Clouds drawing after post-processing stack v2

### ISSUE THREAD

**Issue by Barbelot** [yangrc1234/VolumeCloud#6]
Hello,

Thanks for the great asset ! I have been trying to use it with the post-processing stack v2 however the clouds are not affected by the post-processes. It's as if the clouds are rendered after the post-processes. Any idea what might cause this issue ? 

I just used the VolumeCloud folder in a project with the last post-processing package from the package manager.

Have a nice day.

**Comment by yangrc1234** [comment]
Hi Barbelot,

I don't have any problem using pps with cloud together. Maybe you put the scripts in the wrong order, the cloud rendering script should be above the pps script(which means you render cloud first and do post-processing). If you still have the problem, uploading a sample project would be great.

**Comment by Barbelot** [comment]
Hello,
Thanks for your fast answer, here is a minimal project with only VolumeCloud and PostProcessing package. I added in the test scene the cloud renderer script above the post-processing layer script but the clouds are always drawn on top (especially visible with the vignette post process).

https://we.tl/t-DuFUutCz6f

Thanks for your help.

**Comment by yangrc1234** [comment]
It looks like that the pps v2 is using a CommandBuffer to inject post-processing effects, and its order is BeforeImageEffects, which is before the OnRenderImage(). So maybe I need to edit the code to use CommandBuffer as well, but I don't have much time for now.

I'd suggest you try the repo at https://github.com/GuitarBro/VolumeCloud/tree/StackV2. @GuitarBro made a version of volume cloud that works as part of pps v2.

**Comment by Barbelot** [comment]
Thanks, the version from @GuitarBro works fine !

**Comment by GuitarBro** [comment]
Just a heads-up @Barbelot, my version isn't quite up to date with master here. It's a real pain to try and translate v1 into v2 so I never got around to doing the most recent stuff yangrc worked on. If you'd like to submit a pull request to bring it up to speed, feel free.
